### ISSUE TITLE
SVG?

### ISSUE THREAD

**Issue by mathiasbynens** [11ty/11ty-logo#1]
Can't this be SVG?

**Comment by zachleat** [comment]
Yeah! Might be trivial with https://www.npmjs.com/package/@spurtli/text-to-svg

**Comment by zachleat** [comment]
Or just, like, doing it manually—but gross

**Comment by DirtyF** [comment]
@mathiasbynens https://github.com/11ty/11ty-logo/blob/master/img/logo.svg
font: https://fonts.google.com/specimen/BenchNine

**Comment by alrra** [comment]
> Can't this be SVG?

@mathiasbynens There is [one](https://github.com/11ty/11ty-logo/blob/babbadb8e813b74446c5881772428460fea10df6/img/logo.svg) now, so I think this issue can be closed.

@zachleat When you have some time can you take a look at #4? Thank you!

**Comment by zachleat** [comment]
Merged, thank you!
